export const competitors = [
  "Taichi",
  "Will Ospreay",
  "Jay White",
  "Kota Ibushi",
  "Minoru Suzuki",
  "Kazuchika Okada",
  "Jeff Cobb",
  "Tomohiro Ishii",
  "Shingo Takagi",
  "Yujiro Takahashi",
  "Juice Robinson",
  "Toru Yano",
  "Tetsuya Naito",
  "Zack Sabre Jr.",
  "KENTA",
  "Hirooki Goto",
  "SENADA",
  "Hiroshi Tanahashi",
  "YOSHI-HASHI",
  "EVIL",
];
